### ISSUE TITLE
Osmium error: location for one or more nodes not found in node location index

### ISSUE THREAD

**Issue by bdesteph** [osmcode/node-osmium#105]
LocationHander seems to not work.
Is there an issue with my file or with my code ?
I think the code is pretty straightforward but still, it gives me the following error:

```
/home/intern/Documents/turf/turf-node-example/node_modules/osmium/lib/osmium.js:110
        return osmium.apply_.apply(this, arguments);
                             ^

Error: osmium error: location for one or more nodes not found in node location index
    at Object.exports.apply (/home/intern/Documents/turf/turf-node-example/node_modules/osmium/lib/osmium.js:110:30)
    at Object.<anonymous> (/home/intern/Documents/turf/turf-node-example/index.js:21:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Here is my code:
```
var osmium = require('osmium');
var reader = new osmium.Reader("./input/OSM_Wallonie.osm");
var location_handler = new osmium.LocationHandler("sparse_mem_array");
var handler = new osmium.Handler();

osmium.apply(reader, location_handler,  handler);
```

And the file is correct, even osmium-tools doesn't find any issue:
```
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' generator='JOSM'>
  <node id='-95460280' action='modify' visible='true' lat='50.71983500771' lon='4.58880092382' />
  <node id='-95460281' action='modify' visible='true' lat='50.71976878015' lon='4.59111835241' />
  <node id='-95460283' action='modify' visible='true' lat='50.71855289353' lon='4.59863658428' />
  <node id='-95460285' action='modify' visible='true' lat='50.7670825166' lon='4.52362026215' />
  <node id='-95460286' action='modify' visible='true' lat='50.77511611253' lon='4.55692256927' />
  <node id='-95460288' action='modify' visible='true' lat='50.78336539659' lon='4.53941310883' />
  <way id='-95460282' action='modify' visible='true'>
    <nd ref='-95460280' />
    <nd ref='-95460281' />
    <nd ref='-95460283' />
  </way>
  <way id='-95460287' action='modify' visible='true'>
    <nd ref='-95460285' />
    <nd ref='-95460286' />
    <nd ref='-95460288' />
  </way>
</osm>
```

**Comment by joto** [comment]
The file you are quoting is from JOSM, it is not a normal OSM file. You'll get into problems with the negative IDs at least, there might be other problems as the JOSM file format is very similar, but not the same as normal OSM files. And unlike most other Osmium code, node-osmium doesn't support negative IDs. You can try `osmium renumber` on it, but I am not sure it will work.

**Comment by ChulhoonJang** [comment]
I had the same problem, but after renaming the negative number to the positive, it worked. Thank you. @joto 

> The file you are quoting is from JOSM, it is not a normal OSM file. You'll get into problems with the negative IDs at least, there might be other problems as the JOSM file format is very similar, but not the same as normal OSM files. And unlike most other Osmium code, node-osmium doesn't support negative IDs. You can try `osmium renumber` on it, but I am not sure it will work.
