### ISSUE TITLE
MultipolygonCollector read_relations fails with Reader

### ISSUE THREAD

**Issue by matburnham** [osmcode/node-osmium#106]
I'm trying to get a location polygon for relations, and am hoping `MultipolygonCollector `will do this for me. The following code is derived from the [tutorial](https://github.com/osmcode/node-osmium/blob/master/doc/tutorial.md#working-with-multipolygons)):

```
const osmium = require('osmium');
var mp = new osmium.MultipolygonCollector();
var reader = new osmium.Reader('osm.pbf');
mp.read_relations(reader);
reader.close();
```

I get a bit of an odd error:

```
test.js:4
mp.read_relations(reader);
   ^

Error: call MultipolygonCollector.read_relation() with BasicReader or Buffer object
    at Object.<anonymous> (test.js:6:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

It looks like the error arrives from lines [55](https://github.com/osmcode/node-osmium/blob/master/src/multipolygon_collector_wrap.cpp#L55) or [66](https://github.com/osmcode/node-osmium/blob/master/src/multipolygon_collector_wrap.cpp#L66) of `multipolygon_collector_wrap.cpp`.

**Comment by matburnham** [comment]
Forcing a `BasicReader` seems to fix this:
```
var reader = new osmium.Reader('osm.pbf');
```
Could do with updating the tutorial as this has taken me some time to track down.
