### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by aaronlidman** [osmcode/node-osmium#41]
Just hit this issue on Ubuntu 14.04. The same code works fine on OS X.

via npm install
```js
> osmium@0.3.0 install /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v11-linux-x64.tar.gz
[osmium] Success: "/mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node" is reinstalled via remote

```

So it installs but when actually using it, it runs for a while, then results in:
```
Segmentation fault (core dumped)
```

Code I'm running is here: https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/blob/master/data/index.js

**Comment by springmeyer** [comment]
The `invalid ELF header` is happening because somehow I accidentally published an osx binary for the linux one. However, this is problem is being caught dynamically by node-pre-gyp and the correct binary is being used in the end. As far as the Segfault: I am unable to replicate. If this happens to you again do:

```
ulimit -c unlimited -S
node <your script>
# then if a segfault happens do:
gdb `which node` core* -ex "thread apply all bt" -ex "set pagination 0" -batch
```

And then share the result.

**Comment by aaronlidman** [comment]
@springmeyer Here are the results.

```
root@ip-172-31-43-180:/mnt/mapbox-studio-humanitarian-print.tm2/data# gdb `which node` core* -ex "thread apply all bt" -ex "set pagination 0" -batch

warning: core file may not match specified executable file.
[New LWP 17484]
[New LWP 17485]
[New LWP 17486]
[New LWP 17487]
[New LWP 17488]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `node index.js latest.osm.pbf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdccfd89f89 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node

Thread 5 (Thread 0x7fdcceb2d700 (LWP 17488)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007fdccfd7cbb1 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fdccfd7c733 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fdcd4cd5bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fdcd4a0e182 in start_thread (arg=0x7fdcceb2d700) at pthread_create.c:312
#5  0x00007fdcd473b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7fdccf32e700 (LWP 17487)):
#0  0x00007fdcd4a15b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fdccfd76dc6 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fdcd4cd5bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fdcd4a0e182 in start_thread (arg=0x7fdccf32e700) at pthread_create.c:312
#4  0x00007fdcd473b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7fdccfb2f700 (LWP 17486)):
#0  0x00007fdcd4a15b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fdccfd9a61e in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fdccfd9a49f in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fdccfd70249 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#4  0x00007fdccfd70085 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#5  0x00007fdccfd7029e in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#6  0x00007fdcd4a13a90 in pthread_once () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:103
#7  0x00007fdccfd9a2f6 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#8  0x00007fdcd4cd5bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fdcd4a0e182 in start_thread (arg=0x7fdccfb2f700) at pthread_create.c:312
#10 0x00007fdcd473b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7fdcd65b1700 (LWP 17485)):
#0  0x00007fdcd4701f3d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fdcd47334a4 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
#2  0x00007fdcd5c46000 in ?? () from /usr/lib/libv8.so.3.14.5
#3  0x00007fdcd5c45cc6 in ?? () from /usr/lib/libv8.so.3.14.5
#4  0x00007fdcd4a0e182 in start_thread (arg=0x7fdcd65b1700) at pthread_create.c:312
#5  0x00007fdcd473b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7fdcd65b3780 (LWP 17484)):
#0  0x00007fdccfd89f89 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#1  0x00007fdccfd895d8 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fdccfd88dff in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fdccfd56410 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#4  0x00007fdccfd5555d in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#5  0x00007fdcd5a06313 in ?? () from /usr/lib/libv8.so.3.14.5
#6  0x00002ef901506362 in ?? ()
#7  0x00002ef9015062c1 in ?? ()
#8  0x00007fffd2290910 in ?? ()
#9  0x00007fffd2290998 in ?? ()
#10 0x00002ef901564f22 in ?? ()
#11 0x00003f7277b58239 in ?? ()
#12 0x00000c750c915419 in ?? ()
#13 0x00000c750c915439 in ?? ()
#14 0x00000c750c915459 in ?? ()
#15 0x00000c750c915479 in ?? ()
#16 0x00000c750c9153d1 in ?? ()
#17 0x00000c750c915419 in ?? ()
#18 0x00000c750c915439 in ?? ()
#19 0x00000c750c915459 in ?? ()
#20 0x00000c750c915491 in ?? ()
#21 0x00000c750c915479 in ?? ()
#22 0x00000c750c9154b1 in ?? ()
#23 0x00000c750c9154f9 in ?? ()
#24 0x00007fffd2290a00 in ?? ()
#25 0x00002ef9015123fe in ?? ()
#26 0x00000c750c915531 in ?? ()
#27 0x00002b07e3f3cc19 in ?? ()
#28 0x00000c750c915559 in ?? ()
#29 0x00000c750c9155e1 in ?? ()
#30 0x00000c750c915629 in ?? ()
#31 0x00000c750c915629 in ?? ()
#32 0x0000000500000000 in ?? ()
#33 0x0000000500000000 in ?? ()
#34 0x00002ef901512241 in ?? ()
#35 0x0000000600000000 in ?? ()
#36 0x00000c750c915641 in ?? ()
#37 0x00007fffd2290a70 in ?? ()
#38 0x00002ef901564690 in ?? ()
#39 0x00000c750c915861 in ?? ()
#40 0x00000c750c915629 in ?? ()
#41 0x00000c750c9154b1 in ?? ()
#42 0x00000c750c915861 in ?? ()
#43 0x00000c750c9154b1 in ?? ()
#44 0x00002b07e3f3cca1 in ?? ()
#45 0x00003f7277b04121 in ?? ()
#46 0x00003f7277b04121 in ?? ()
#47 0x00000c750c915531 in ?? ()
#48 0x00000c750c9155e1 in ?? ()
#49 0x00003f7277b45f69 in ?? ()
#50 0x00000c750c915881 in ?? ()
#51 0x00007fffd2290ab0 in ?? ()
#52 0x00002ef90155f265 in ?? ()
#53 0x00002b07e3f3cc19 in ?? ()
#54 0x00002b07e3f3d171 in ?? ()
#55 0x00000c750c915559 in ?? ()
#56 0x00002b07e3f3d171 in ?? ()
#57 0x00003f7277b45fe9 in ?? ()
#58 0x00000c750c9158b9 in ?? ()
#59 0x00007fffd2290af8 in ?? ()
#60 0x00002ef90155b376 in ?? ()
#61 0x00002b07e3f3cc19 in ?? ()
#62 0x00000c750c915559 in ?? ()
#63 0x00000c750c915971 in ?? ()
#64 0x00002b07e3f3d5f9 in ?? ()
#65 0x00002b07e3f3d5f9 in ?? ()
#66 0x00003f7277b45ed9 in ?? ()
#67 0x00000c750c9158b9 in ?? ()
#68 0x00007fffd2290b78 in ?? ()
#69 0x00002ef90154a687 in ?? ()
#70 0x00002b07e3f3cc19 in ?? ()
#71 0x00000c750c915559 in ?? ()
#72 0x00007fffd2290cb0 in ?? ()
#73 0x00002ef90154a1c1 in ?? ()
#74 0x0000000000000002 in ?? ()
#75 0x00000c750c9158b9 in ?? ()
#76 0x00007fffd2290b78 in ?? ()
#77 0x00003f7277b04141 in ?? ()
#78 0x00000c750c915559 in ?? ()
#79 0x00003f7277b04121 in ?? ()
#80 0x00003f7277b04121 in ?? ()
#81 0x00002b07e3f3cc19 in ?? ()
#82 0x00003f7277b45e49 in ?? ()
#83 0x00000c750c9158b9 in ?? ()
#84 0x00007fffd2290bb8 in ?? ()
#85 0x00002ef90154a04b in ?? ()
#86 0x00003f7277b04141 in ?? ()
#87 0x00003f7277b04101 in ?? ()
#88 0x00002b07e3f3d619 in ?? ()
#89 0x00000c750c915989 in ?? ()
#90 0x00003f7277b46079 in ?? ()
#91 0x00000c750c9158b9 in ?? ()
#92 0x00007fffd2290c20 in ?? ()
#93 0x00002ef90152e159 in ?? ()
#94 0x00000c750c915989 in ?? ()
#95 0x00003f7277b04121 in ?? ()
#96 0x00003f7277b04121 in ?? ()
#97 0x00003f7277b04121 in ?? ()
#98 0x00000c750c915989 in ?? ()
#99 0x00003f7277b04121 in ?? ()
#100 0x00000c750c9159d1 in ?? ()
#101 0x00003f7277b04121 in ?? ()
#102 0x00000c750c9159e9 in ?? ()
#103 0x00000c750c915a31 in ?? ()
#104 0x00000c750c915a79 in ?? ()
#105 0x00007fffd2290c58 in ?? ()
#106 0x00002ef90152d6e5 in ?? ()
#107 0x00003f7277b06c91 in ?? ()
#108 0x00000c750c915a31 in ?? ()
#109 0x00003f7277b34629 in ?? ()
#110 0x00000c750c915ab1 in ?? ()
#111 0x00000c750c915af9 in ?? ()
#112 0x00007fffd2290c98 in ?? ()
#113 0x00002ef90150d607 in ?? ()
#114 0x00000c750c915b69 in ?? ()
#115 0x00003f7277b06c91 in ?? ()
#116 0x00000c750c915ab1 in ?? ()
#117 0x00002ef90150d541 in ?? ()
#118 0x0000000600000000 in ?? ()
#119 0x0000000000000000 in ?? ()
```

and it's still hitting the ELF header issue:
```
[osmium] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v11-linux-x64.tar.gz
```

Let me know how I can help.

**Comment by springmeyer** [comment]
can you try running mode v0.10.38 installed via nvm. I have a hunch that the problem is related to RH ubuntu build of node.

**Comment by aaronlidman** [comment]
The issue persisted using v0.10.38.

```
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# nvm current
v0.10.38
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# npm install
npm WARN package.json hot-tags@0.0.0 No repository field.
-
> osmium@0.3.0 install /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:565:25)
    at startup (node.js:80:7)
    at node.js:935:3

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
[osmium] Success: "/mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node" is reinstalled via remote
mapbox-upload@3.1.0 node_modules/mapbox-upload
├── minimist@1.1.1
├── progress-stream@0.5.0 (single-line-log@0.3.1, speedometer@0.1.4, through2@0.2.3)
├── request@2.55.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, bl@0.9.4, http-signature@0.10.1, tough-cookie@1.1.0, hawk@2.3.1, har-validator@1.7.0)
├── s3-upload-stream@0.6.2 (aws-sdk@2.0.15)
└── aws-sdk@2.0.29 (xmlbuilder@0.4.2, xml2js@0.2.6)

osmium@0.3.0 node_modules/osmium
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# node index.js latest.osm.pbf > output.geojson
Segmentation fault (core dumped)
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# ulimit -c unlimited -S
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# node index.js latest.osm.pbf > output.geojson
Segmentation fault (core dumped)
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# gdb `which node` core* -ex "thread apply all bt" -ex "set pagination 0" -batch
The program 'gdb' can be found in the following packages:
 * gdb
 * gdb-minimal
Try: apt-get install <selected package>
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# apt-get install -y gdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libc6-dbg libpython3.4
Suggested packages:
  gdb-doc gdbserver
Recommended packages:
  libc-dbg
The following NEW packages will be installed:
  gdb libc6-dbg libpython3.4
0 upgraded, 3 newly installed, 0 to remove and 40 not upgraded.
Need to get 6,953 kB of archives.
After this operation, 33.7 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main libpython3.4 amd64 3.4.0-2ubuntu1 [1,303 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main gdb amd64 7.7.1-0ubuntu5~14.04.2 [2,198 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libc6-dbg amd64 2.19-0ubuntu6.6 [3,452 kB]
Fetched 6,953 kB in 0s (44.8 MB/s)
Selecting previously unselected package libpython3.4:amd64.
(Reading database ... 59491 files and directories currently installed.)
Preparing to unpack .../libpython3.4_3.4.0-2ubuntu1_amd64.deb ...
Unpacking libpython3.4:amd64 (3.4.0-2ubuntu1) ...
Selecting previously unselected package gdb.
Preparing to unpack .../gdb_7.7.1-0ubuntu5~14.04.2_amd64.deb ...
Unpacking gdb (7.7.1-0ubuntu5~14.04.2) ...
Selecting previously unselected package libc6-dbg:amd64.
Preparing to unpack .../libc6-dbg_2.19-0ubuntu6.6_amd64.deb ...
Unpacking libc6-dbg:amd64 (2.19-0ubuntu6.6) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libpython3.4:amd64 (3.4.0-2ubuntu1) ...
Setting up gdb (7.7.1-0ubuntu5~14.04.2) ...
Setting up libc6-dbg:amd64 (2.19-0ubuntu6.6) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
root@ip-172-31-35-176:/mnt/mapbox-studio-humanitarian-print.tm2/data# gdb `which node` core* -ex "thread apply all bt" -ex "set pagination 0" -batch
[New LWP 32177]
[New LWP 32178]
[New LWP 32179]
[New LWP 32180]
[New LWP 32181]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `node index.js latest.osm.pbf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fea79a75f89 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node

Thread 5 (Thread 0x7fea6bfff700 (LWP 32181)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007fea79a68bb1 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fea79a68733 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fea7a89cbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fea7a0b9182 in start_thread (arg=0x7fea6bfff700) at pthread_create.c:312
#5  0x00007fea79de647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7fea78e01700 (LWP 32180)):
#0  0x00007fea7a0c0b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fea79a62dc6 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fea7a89cbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fea7a0b9182 in start_thread (arg=0x7fea78e01700) at pthread_create.c:312
#4  0x00007fea79de647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7fea79602700 (LWP 32179)):
#0  0x00007fea7a0c0b9d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fea79a8661e in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fea79a8649f in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fea79a5c249 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#4  0x00007fea79a5c085 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#5  0x00007fea79a5c29e in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#6  0x00007fea7a0bea90 in pthread_once () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:103
#7  0x00007fea79a862f6 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#8  0x00007fea7a89cbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fea7a0b9182 in start_thread (arg=0x7fea79602700) at pthread_create.c:312
#10 0x00007fea79de647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7fea7b10e700 (LWP 32178)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00000000009775e5 in v8::internal::LinuxSemaphore::Wait() ()
#2  0x0000000000882ee7 in v8::internal::RuntimeProfiler::WaitForSomeIsolateToEnterJS() ()
#3  0x0000000000978788 in v8::internal::SignalSender::Run() ()
#4  0x0000000000977818 in v8::internal::ThreadEntry(void*) ()
#5  0x00007fea7a0b9182 in start_thread (arg=0x7fea7b10e700) at pthread_create.c:312
#6  0x00007fea79de647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7fea7b110780 (LWP 32177)):
#0  0x00007fea79a75f89 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#1  0x00007fea79a755d8 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#2  0x00007fea79a74dff in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#3  0x00007fea79a42410 in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#4  0x00007fea79a4155d in ?? () from /mnt/mapbox-studio-humanitarian-print.tm2/data/node_modules/osmium/lib/binding/osmium.node
#5  0x000000000070fdc7 in v8::internal::Builtin_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>, v8::internal::Isolate*) ()
#6  0x00002f72e2e06362 in ?? ()
#7  0x00002f72e2e062c1 in ?? ()
#8  0x00007fffdf520d30 in ?? ()
#9  0x00007fffdf520db8 in ?? ()
#10 0x00002f72e2e66e82 in ?? ()
#11 0x00003a224f957ff9 in ?? ()
#12 0x0000339fab814a69 in ?? ()
#13 0x0000339fab814a89 in ?? ()
#14 0x0000339fab814aa9 in ?? ()
#15 0x0000339fab814ac9 in ?? ()
#16 0x0000339fab814ae1 in ?? ()
#17 0x0000339fab814a69 in ?? ()
#18 0x0000339fab814a89 in ?? ()
#19 0x0000339fab814aa9 in ?? ()
#20 0x0000339fab814b29 in ?? ()
#21 0x0000339fab814ac9 in ?? ()
#22 0x0000339fab814b49 in ?? ()
#23 0x0000339fab814b91 in ?? ()
#24 0x00007fffdf520e20 in ?? ()
#25 0x00002f72e2e122be in ?? ()
#26 0x0000339fab814bc9 in ?? ()
#27 0x0000051ef6e3bf41 in ?? ()
#28 0x0000339fab814bf1 in ?? ()
#29 0x0000339fab814c79 in ?? ()
#30 0x0000339fab814cc1 in ?? ()
#31 0x0000339fab814cc1 in ?? ()
#32 0x0000000500000000 in ?? ()
#33 0x0000000500000000 in ?? ()
#34 0x00002f72e2e12101 in ?? ()
#35 0x0000000600000000 in ?? ()
#36 0x0000339fab814849 in ?? ()
#37 0x00007fffdf520e90 in ?? ()
#38 0x00002f72e2e665f0 in ?? ()
#39 0x0000339fab814cd9 in ?? ()
#40 0x0000339fab814cc1 in ?? ()
#41 0x0000339fab814b49 in ?? ()
#42 0x0000339fab814cd9 in ?? ()
#43 0x0000339fab814b49 in ?? ()
#44 0x0000051ef6e3bfc9 in ?? ()
#45 0x00003a224f904121 in ?? ()
#46 0x00003a224f904121 in ?? ()
#47 0x0000339fab814bc9 in ?? ()
#48 0x0000339fab814c79 in ?? ()
#49 0x00003a224f945ce9 in ?? ()
#50 0x0000339fab814cf9 in ?? ()
#51 0x00007fffdf520ed0 in ?? ()
#52 0x00002f72e2e61385 in ?? ()
#53 0x0000051ef6e3bf41 in ?? ()
#54 0x0000051ef6e3c499 in ?? ()
#55 0x0000339fab814bf1 in ?? ()
#56 0x0000051ef6e3c499 in ?? ()
#57 0x00003a224f945d69 in ?? ()
#58 0x0000339fab814d31 in ?? ()
#59 0x00007fffdf520f18 in ?? ()
#60 0x00002f72e2e5d496 in ?? ()
#61 0x0000051ef6e3bf41 in ?? ()
#62 0x0000339fab814bf1 in ?? ()
#63 0x0000339fab814de9 in ?? ()
#64 0x0000051ef6e3c921 in ?? ()
#65 0x0000051ef6e3c921 in ?? ()
#66 0x00003a224f945c59 in ?? ()
#67 0x0000339fab814d31 in ?? ()
#68 0x00007fffdf520f98 in ?? ()
#69 0x00002f72e2e4af67 in ?? ()
#70 0x0000051ef6e3bf41 in ?? ()
#71 0x0000339fab814bf1 in ?? ()
#72 0x00007fffdf5210d0 in ?? ()
#73 0x00002f72e2e4aaa1 in ?? ()
#74 0x0000000000000002 in ?? ()
#75 0x0000339fab814d31 in ?? ()
#76 0x00007fffdf520f98 in ?? ()
#77 0x00003a224f904141 in ?? ()
#78 0x0000339fab814bf1 in ?? ()
#79 0x00003a224f904121 in ?? ()
#80 0x00003a224f904121 in ?? ()
#81 0x0000051ef6e3bf41 in ?? ()
#82 0x00003a224f945bc9 in ?? ()
#83 0x0000339fab814d31 in ?? ()
#84 0x00007fffdf520fd8 in ?? ()
#85 0x00002f72e2e4a92b in ?? ()
#86 0x00003a224f904141 in ?? ()
#87 0x00003a224f904101 in ?? ()
#88 0x0000051ef6e3c941 in ?? ()
#89 0x0000339fab814e01 in ?? ()
#90 0x00003a224f945df9 in ?? ()
#91 0x0000339fab814d31 in ?? ()
#92 0x00007fffdf521040 in ?? ()
#93 0x00002f72e2e2e239 in ?? ()
#94 0x0000339fab814e01 in ?? ()
#95 0x00003a224f904121 in ?? ()
#96 0x00003a224f904121 in ?? ()
#97 0x00003a224f904121 in ?? ()
#98 0x0000339fab814e01 in ?? ()
#99 0x00003a224f904121 in ?? ()
#100 0x0000339fab814e49 in ?? ()
#101 0x00003a224f904121 in ?? ()
#102 0x0000339fab814e61 in ?? ()
#103 0x0000339fab814ea9 in ?? ()
#104 0x0000339fab814ef1 in ?? ()
#105 0x00007fffdf521078 in ?? ()
#106 0x00002f72e2e2d7bf in ?? ()
#107 0x00003a224f906c91 in ?? ()
#108 0x0000339fab814ea9 in ?? ()
#109 0x00003a224f934709 in ?? ()
#110 0x0000339fab814f29 in ?? ()
#111 0x0000339fab814f71 in ?? ()
#112 0x00007fffdf5210b8 in ?? ()
#113 0x00002f72e2e0d507 in ?? ()
#114 0x0000339fab814fe9 in ?? ()
#115 0x00003a224f906c91 in ?? ()
#116 0x0000339fab814f29 in ?? ()
#117 0x00002f72e2e0d441 in ?? ()
#118 0x0000000600000000 in ?? ()
#119 0x0000000000000000 in ?? ()
```

**Comment by springmeyer** [comment]
okay. thanks for trying. next action: get a new osmium tag out. at the least I will do the new builds to chain symbols. currently they are lacking so we cannot see the exact crash line.

**Comment by springmeyer** [comment]
@aaronlidman - okay, I have published new binaries for the upcoming v0.4.0 release. Can you test them before I tag?

Just point your package.json at latest osmium like:

```js
"osmium": "https://github.com/osmcode/node-osmium/tarball/master",
```

**Comment by aaronlidman** [comment]
@springmeyer Works swimmingly. :+1: :+1: 

Slight breaking change with Reader -> BasicReader, but not a huge deal.

**Comment by springmeyer** [comment]
great that works. trying to address the breaking change at https://github.com/osmcode/node-osmium/pull/43

**Comment by aaronlidman** [comment]
Next actions at #43

Looking forward to the next release.
