### ISSUE TITLE
Problem with osmium

### ISSUE THREAD

**Issue by idir-ait** [osmcode/node-osmium#45]
hello everyone

can you help me with osmuim i can't install it on my server :

i have the next msg :

$ npm install osmium
/
> osmium@0.3.0 install /home/julien/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/julien/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download
[osmium] Success: "/home/julien/node_modules/osmium/lib/binding/osmium.node" is reinstalled via remote
osmium@0.3.0 ../node_modules/osmium

and when i try to execute my programme i have :

$ node loadParking.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/julien/node_modules/osmium/lib/binding/osmium.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/julien/node_modules/osmium/lib/osmium.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by springmeyer** [comment]
the first error is harmless but will be fixed in the next release. the second error is because you are running on a system with a libstdc++ too old to support C++11. To solve this you either need to run a more recent linux version or you need to upgrade your libstdc++. To upgrade install libstdc++ from ppa:ubuntu-toolchain-r/test

**Comment by idir-ait** [comment]
i have le latest version :/ ??!
~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by springmeyer** [comment]
should be fixed by the v0.4.0 release (#38)
