### ISSUE TITLE
installation is failing

### ISSUE THREAD

**Issue by aaronpdennis** [osmcode/node-osmium#47]
Installing this package on OS X is failing.

```
$ npm install osmium
npm WARN engine osmium@0.3.0: wanted: {"node":">= 0.10.0 < 0.11.0"} (current: {"node":"0.12.6","npm":"2.12.1"})

> osmium@0.3.0 install /Users/aaron/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed: /usr/local/Cellar/node/0.12.6/bin/node --eval require('/Users/aaron/node_modules/osmium/lib/binding/osmium.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/osmium/src/apply.o
../src/apply.cpp:10:10: fatal error: 'osmium/io/input_iterator.hpp' file not
      found
#include <osmium/io/input_iterator.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/osmium/src/apply.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=osmium" "--configuration=Release" "--module_name=osmium" "--version=0.3.0" "--minor=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/osmium.js" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/aaron/node_modules/osmium/lib/binding" "--module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node" "--remote_path=./osmium/v0.3.0/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/aaron/node_modules/osmium
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/aaron/node_modules/osmium/lib/binding --module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aaron/node_modules/osmium/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/Users/aaron/node_modules/osmium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/aaron/node_modules/osmium
node-pre-gyp ERR! node -v v0.12.6
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/aaron/node_modules/osmium/lib/binding --module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "osmium"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! osmium@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osmium@0.3.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the osmium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls osmium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron/Desktop/test/npm-debug.log
```
And for development installation method:
```
$ make
npm install node-pre-gyp
npm WARN package.json osmium@0.4.0 No license field.
npm WARN installMany node-pre-gyp was bundled with osmium@0.4.0, but bundled package wasn't found in unpacked tree
node-pre-gyp@0.6.7 node_modules/node-pre-gyp
npm install `node -e "console.log(Object.keys(require('./package.json').dependencies).join(' '))"` \
	`node -e "console.log(Object.keys(require('./package.json').devDependencies).join(' '))"` --clang=1
npm WARN package.json osmium@0.4.0 No license field.
mocha@2.2.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── growl@1.8.1
├── diff@1.4.0
├── commander@2.3.0
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

aws-sdk@2.1.36 node_modules/aws-sdk
├── xmlbuilder@0.4.2
├── xml2js@0.2.8
└── sax@0.5.3

node-pre-gyp@0.6.7 node_modules/node-pre-gyp
./node_modules/.bin/node-pre-gyp configure --loglevel=error --clang=1
node-pre-gyp ERR! configure error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --loglevel=error --clang=1 --module=/Users/aaron/Desktop/test/node-osmium/lib/binding/osmium.node --module_name=osmium --module_path=/Users/aaron/Desktop/test/node-osmium/lib/binding' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aaron/Desktop/test/node-osmium/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:107:17)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:12)
node-pre-gyp ERR! stack     at child_process.js:1144:20
node-pre-gyp ERR! stack     at process._tickCallback (node.js:355:11)
node-pre-gyp ERR! stack     at Function.Module.runMain (module.js:503:11)
node-pre-gyp ERR! stack     at startup (node.js:129:16)
node-pre-gyp ERR! stack     at node.js:814:3
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/Users/aaron/Desktop/test/node-osmium/node_modules/.bin/node-pre-gyp" "configure" "--loglevel=error" "--clang=1"
node-pre-gyp ERR! cwd /Users/aaron/Desktop/test/node-osmium
node-pre-gyp ERR! node -v v0.12.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp configure --loglevel=error --clang=1 --module=/Users/aaron/Desktop/test/node-osmium/lib/binding/osmium.node --module_name=osmium --module_path=/Users/aaron/Desktop/test/node-osmium/lib/binding' (Error: spawn node-gyp ENOENT)
make: *** [build] Error 1
```

**Comment by aaronpdennis** [comment]
`npm install --build-from-source` with v0.3.0 release also failed

**Comment by springmeyer** [comment]
@aaronpdennis this error is really odd and indicates something wrong with xcode on your system:

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by aaronpdennis** [comment]
@springmeyer thanks for the help! I was stuck there for awhile

**Comment by aaronpdennis** [comment]
I'm still unable to install :/

```
$npm install osmium
npm WARN engine osmium@0.3.0: wanted: {"node":">= 0.10.0 < 0.11.0"} (current: {"node":"0.12.6","npm":"2.12.1"})

> osmium@0.3.0 install /Users/aaron/node_modules/osmium
> node-pre-gyp install --fallback-to-build

[osmium] Command failed: /usr/local/Cellar/node/0.12.6/bin/node --eval require('/Users/aaron/node_modules/osmium/lib/binding/osmium.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/osmium/src/apply.o
../src/apply.cpp:10:10: fatal error: 'osmium/io/input_iterator.hpp' file not
      found
#include <osmium/io/input_iterator.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/osmium/src/apply.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=osmium" "--configuration=Release" "--module_name=osmium" "--version=0.3.0" "--minor=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/osmium.js" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/aaron/node_modules/osmium/lib/binding" "--module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node" "--remote_path=./osmium/v0.3.0/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/aaron/node_modules/osmium
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/aaron/node_modules/osmium/lib/binding --module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aaron/node_modules/osmium/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/Users/aaron/node_modules/osmium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/aaron/node_modules/osmium
node-pre-gyp ERR! node -v v0.12.6
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp rebuild --name=osmium --configuration=Release --module_name=osmium --version=0.3.0 --minor=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/osmium.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/aaron/node_modules/osmium/lib/binding --module=/Users/aaron/node_modules/osmium/lib/binding/osmium.node --remote_path=./osmium/v0.3.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/osmium/v0.3.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.3.0/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "osmium"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! osmium@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osmium@0.3.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the osmium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls osmium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron/Desktop/test/npm-debug.log
```

**Comment by springmeyer** [comment]
Two problems now:

 - You need to also install libosmium
 - However you are also using Node v0.12.x which node-osmium is not compatible with yet

So I recommend you downgrade node to v0.10.x. Then binaries will be available and you won't need to install an external libosmium (nor ever worry about a source compile).

**Comment by aaronpdennis** [comment]
@springmeyer thanks for all your help! successfully installed
