### ISSUE TITLE
Error on processing big files ,using location_handler.

### ISSUE THREAD

**Issue by Rub21** [osmcode/node-osmium#58]
```
/home/ruben/apps/osm-count/node_modules/osmium/lib/osmium.js:103
        return osmium.apply_.apply(this, arguments);
                             ^
Error: osmium error: location for one or more nodes not found in node location index
    at Object.exports.apply (/home/ruben/apps/osm-count/node_modules/osmium/lib/osmium.js:103:30)
    at Object.<anonymous> (/home/ruben/apps/osm-count/index.js:84:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

file : https://s3.amazonaws.com/mapbox/playground/ruben/mexico.osm.bz2

**Comment by morganherlocker** [comment]
Usually this error is due to a way referencing a node that does not exist in the file.

**Comment by joto** [comment]
You can check for this using the osmium command line tool (https://github.com/osmcode/osmium-tool):

    > osmium check-refs mexico.osm.bz2
    There are 768993 nodes, 97175 ways, and 117 relations in this file.
    Nodes in ways missing: 91715

`osmium fileinfo mexico.osm.bz2` tells me `osmconvert` was used to create this file. I you didn't use the `--complete-ways` option when doing this.

**Comment by sahilgoel1610** [comment]
Is there any workaround to this? may be skip the way when this error occurs?
