### ISSUE TITLE
Test failure on multipolygons

### ISSUE THREAD

**Issue by joto** [osmcode/node-osmium#65]
Tests for multipolygons fail suddenly. New turf-difference module version? @rclark can you take a look?

```
  1) 749: Valid multipolygon with two outer rings. generated fixed wkt for invalid area 749800:
     side location conflict [ (7.93, 1.46) ]
  Error
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/lib/jsts.js:21:414)
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/index.js:2:12)
      at Object.<anonymous> (node_modules/turf-difference/index.js:2:12)
      at Object.<anonymous> (test/osm-testdata.test.js:8:18)
      at Array.forEach (native)
      at node.js:906:3

  2) 749: Valid multipolygon with two outer rings. generated fixed geojson for invalid area 749800:
     side location conflict [ (7.93, 1.46) ]
  Error
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/lib/jsts.js:21:414)
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/index.js:2:12)
      at Object.<anonymous> (node_modules/turf-difference/index.js:2:12)
      at Object.<anonymous> (test/osm-testdata.test.js:8:18)
      at Array.forEach (native)
      at node.js:906:3

  3) 767: Single way going back on itself. generated wkt area for feature 767800:
     unable to assign hole to a shell [ (7.78, 1.63) ]
  Error
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/lib/jsts.js:21:414)
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/index.js:2:12)
      at Object.<anonymous> (node_modules/turf-difference/index.js:2:12)
      at Object.<anonymous> (test/osm-testdata.test.js:8:18)
      at Array.forEach (native)
      at node.js:906:3

  4) 767: Single way going back on itself. generated geojson area for feature 767800:
     unable to assign hole to a shell [ (7.78, 1.63) ]
  Error
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/lib/jsts.js:21:414)
      at Object.<anonymous> (node_modules/turf-difference/node_modules/jsts/index.js:2:12)
      at Object.<anonymous> (node_modules/turf-difference/index.js:2:12)
      at Object.<anonymous> (test/osm-testdata.test.js:8:18)
      at Array.forEach (native)
      at node.js:906:3
```

**Comment by rclark** [comment]
I wasn't able to reproduce this locally:

```
$ git pull master
$ make clean
$ CXXFLAGS=-I/usr/local/include make
$ node_modules/.bin/mocha test/osm-testdata.test.js
$ npm test
```

Are you seeing these failures on a branch? There hasn't been a new version of turf-difference since March.

turf-difference is being used to assert equality between shapes. Unfortunately I found that its error messages were not very helpful when it is fed invalid data from node-osmium. If you have any other ideas for checking equality in JavaScript I would be very open to it.

**Comment by joto** [comment]
Today I can not reproduce this myself. Strange.
