### ISSUE TITLE
Error: osmium error: std::bad_alloc

### ISSUE THREAD

**Issue by teehamaral** [osmcode/node-osmium#77]
I'm having trouble using osmium lib to extract geoson from a .pbf file. The error is the following:

```
mapzen_env)root@ip-172-31-50-249:~/node-osmium# osm2geojson -w -n /home/ubuntu/data/ireland.pbf
/usr/local/lib/node_modules/osm2geojson/node_modules/osmium/lib/osmium.js:100
    return this._reader.read();
                        ^
Error: osmium error: std::bad_alloc
    at exports.Reader.read (/usr/local/lib/node_modules/osm2geojson/node_modules/osmium/lib/osmium.js:100:25)
    at new exports.Stream (/usr/local/lib/node_modules/osm2geojson/node_modules/osmium/lib/osmium.js:171:31)
    at osm2geojson (/usr/local/lib/node_modules/osm2geojson/index.js:11:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/osm2geojson/bin/osm2geojson.js:28:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```
I did some tests and noticed that the error is possibly related to command `osmium.File(filePath)`. Can anybody help me?

**Comment by joto** [comment]
`bad_alloc` almost certainly means you don't have enough memory.

**Comment by teehamaral** [comment]
Thanks @joto.
