### ISSUE TITLE
basic installation and working

### ISSUE THREAD

**Issue by gagan-bansal** [osmcode/node-osmium#86]
I installed using command
`npm install osmium`
on my CentOS 7.x and it got installed without any error. Got message like this

```
> node-pre-gyp install --fallback-to-build

[osmium] Success: "/home/gaganb/myproject/node_modules/osmium/lib/binding/osmium.node" is installed via remote
myproject@1.0.0 /home/gaganb/myproject
└─┬ osmium@0.5.2
    and many more
```

When I use in node.js I got an error as follows:

```
> var osm = require('osmium')
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/gaganb/myproject/node_modules/osmium/lib/binding/osmium.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gaganb/myproject/node_modules/osmium/lib/osmium.js:4:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

Here is g++ -v output:

```
> [gaganb@localhost myproject]$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
```

Am I doing some very basic mistake?

**Comment by henningvs** [comment]
I had the same issue lately. It worked for me after doing 
```
sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
sudo apt-get -y update
sudo apt-get -y install gcc-4.8 g++-4.8 build-essential 
sudo apt-get -y install libboost-dev zlib1g-dev libexpat1-dev libsparsehash-dev
```
I guess it might be different on CentOS but it seems a problem with not installed dependencies.

**Comment by springmeyer** [comment]
Correct @henningvs - the binaries we provide need an upgraded libstdc++ to run. You can do this on ubuntu like:

```
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update -y
apt-get install -y libstdc++-5-dev
```

On other systems like centos you will need to install gcc 5.

**Comment by joto** [comment]
@springmeyer Shouldn't the install fall back to a local build if the right binary is not available? It seems here, the binary was installed, but it shouldn't have been.

**Comment by springmeyer** [comment]
Ah, okay I will take a look.

**Comment by gagan-bansal** [comment]
Thanks for update, all these libs as mentioned are already installed
```libboost-dev zlib1g-dev libexpat1-dev libsparsehash-dev ```
I'll see how to upgrade to gcc 5.

**Comment by springmeyer** [comment]
>  @springmeyer Shouldn't the install fall back to a local build if the right binary is not available? It seems here, the binary was installed, but it shouldn't have been.

This turns out to be https://github.com/mapbox/node-pre-gyp/issues/270

> the binaries we provide need an upgraded libstdc++ to run

I'll attempt to get the binaries working with an older listdc++ - hitting this in https://github.com/osmcode/node-osmium/pull/90
